### ISSUE TITLE
replication slave cant restart with a MYSQL_MASTER_ROOT_USER  different from root

### ISSUE THREAD

**Issue by icrc-fdeniger** [bitnami/bitnami-docker-mysql#106]
if MYSQL_MASTER_ROOT_USER <> root, it seems we can't restart a replication slave.

Step 1: start docker-compose in the attached archive. The service mysql-repl starts as expected
Step 2: restart the docker-compose. the service mysql-repl can't be restarted: 
` mysql_upgrade: Got error: 1045: Access denied for user 'root'@'localhost' (using password: YES) while connecting to the MySQL server`

[test.zip](https://github.com/bitnami/bitnami-docker-mysql/files/5184864/test.zip)

**Comment by miguelaeh** [comment]
Hi @icrc-fdeniger ,
Thank you very much for reporting this issue. I have been able to reproduce it.
I have been investigating but I didn't found the source of the error. I will create an internal task so we can take a look to this issue in deeper.
Regards.

**Comment by icrc-fdeniger** [comment]
Thanks.
FYI I found another issue that i can't explain yet. With swarm activated,  scripts /docker-entrypoint-initdb.d are executed at restart...

**Comment by icrc-fdeniger** [comment]
Hello, this issue is still there.
You can try with this docker-compose file:

```
version: "3.7"

services:
  mysql:
    image: bitnami/mysql:5.7.31
    ports:
      - 3306:3306
    volumes:
      - mysql-master-data:/bitnami/mysql/data
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_ROOT_USER=root_changed
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_REPLICATION_USER=repl
      - MYSQL_REPLICATION_PASSWORD=repl

  mysql-repl:
    image: bitnami/mysql:5.7.31
    ports:
      - 3307:3306
    volumes:
      - mysql-slave-data:/bitnami/mysql/data
    environment:
      - BITNAMI_DEBUG=true
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_MASTER_HOST=mysql
      - MYSQL_MASTER_PORT_NUMBER=3306
      # To be added at the second start
#      - MYSQL_ROOT_USER=root_changed
      - MYSQL_MASTER_ROOT_USER=root_changed
      - MYSQL_MASTER_ROOT_PASSWORD=pwd
      - MYSQL_REPLICATION_USER=repl
      - MYSQL_REPLICATION_PASSWORD=repl


volumes:
  mysql-master-data:
    name: bitnami-mysql-master-data
    driver: local

  mysql-slave-data:
    name: bitnami-mysql-slave-data
    driver: local

```
