### ISSUE TITLE
MySql group replication in docker swarm not working

### ISSUE THREAD

**Issue by Mike-the-one** [bitnami/bitnami-docker-mysql#119]
**Description**
I am following the wiki to setup a 3 nodes replication on three dedicated hosts, but I am not able to make it working.

**Steps to reproduce the issue:**

1. Setup docker swarm (1 manager, 2 workers)
2. Create the my_custom.cnf on each host
3. Deploy the stack

**Describe the results you received:**

```
mysql_master.1.wnusvzmnltfe@32g-960g-node1    | mysql 20:57:39.65 INFO  ==> ** Starting MySQL **
mysql_master.1.wnusvzmnltfe@32g-960g-node1    | 2020-12-14T20:57:39.866031Z 0 [System] [MY-010116] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.0.22) starting as process 1
mysql_master.1.wnusvzmnltfe@32g-960g-node1    | 2020-12-14T20:57:39.885919Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
mysql_master.1.wnusvzmnltfe@32g-960g-node1    | 2020-12-14T20:57:40.166412Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysql_master.1.wnusvzmnltfe@32g-960g-node1    | 2020-12-14T20:57:40.340442Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /tmp/mysqlx.sock
mysql_master.1.wnusvzmnltfe@32g-960g-node1    | 2020-12-14T20:57:40.465011Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql_master.1.wnusvzmnltfe@32g-960g-node1    | 2020-12-14T20:57:40.465343Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
mysql_master.1.wnusvzmnltfe@32g-960g-node1    | 2020-12-14T20:57:40.490733Z 0 [System] [MY-010931] [Server] /opt/bitnami/mysql/bin/mysqld: ready for connections. Version: '8.0.22'  socket: '/opt/bitnami/mysql/tmp/mysql.sock'  port: 3306  Source distribution.
mysql_master.1.wnusvzmnltfe@32g-960g-node1    | 2020-12-14T20:57:43.350634Z 8 [Warning] [MY-013130] [Server] Aborted connection 8 to db: 'unconnected' user: 'repl_user' host: '192.168.10.199' (init_connect command failed; diagnostics area: MY-001064 - You have an error in your SQL syntax; check the manual that corr)
mysql_master.1.wnusvzmnltfe@32g-960g-node1    | 2020-12-14T20:57:43.353770Z 9 [Warning] [MY-013130] [Server] Aborted connection 9 to db: 'unconnected' user: 'repl_user' host: '192.168.10.199' (init_connect command failed; diagnostics area: MY-001064 - You have an error in your SQL syntax; check the manual that corr)
mysql_master.1.wnusvzmnltfe@32g-960g-node1    | 2020-12-14T20:58:38.619844Z 10 [Warning] [MY-013130] [Server] Aborted connection 10 to db: 'unconnected' user: 'repl_user' host: '192.168.10.202' (init_connect command failed; diagnostics area: MY-001064 - You have an error in your SQL syntax; check the manual that corr)
mysql_master.1.wnusvzmnltfe@32g-960g-node1    | 2020-12-14T20:58:38.624043Z 11 [Warning] [MY-013130] [Server] Aborted connection 11 to db: 'unconnected' user: 'repl_user' host: '192.168.10.202' (init_connect command failed; diagnostics area: MY-001064 - You have an error in your SQL syntax; check the manual that corr)
```

Similar errors on two slaves

**Describe the results you expected:**

I don't expect any errors in log.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
Latest bitnami docker image

- Output of `docker version`: (same for all nodes)

```

Client: Docker Engine - Community
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:59:40 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:57:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: hndvku4qw1jw3241fmc6filgt
  Is Manager: true
  ClusterID: qotgjgwhuvafs0ym8rfno50y3
  Managers: 1
  Nodes: 3
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 158.69.53.176
  Manager Addresses:
   158.69.53.176:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-58-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.1GiB
 Name: 32g-960g-node1
 ID: XSSX:ZQYD:EZY5:PQS4:WWHK:UDSQ:WOWH:Q3JG:72PG:TIRI:2OZG:BRY6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

My `docker-compose.yml` file for the stack:

```yml
version: '3.7'
  
services:
  master:
    image: 'bitnami/mysql:8.0-debian-10'
    user: root
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.tag == node1
    networks:
      - one
    ports:
      - '3306'
    volumes:
      - /home/one/data/mysql/data:/bitnami/mysql/data
      - /home/one/data/mysql/slowlog:/slowlog
      - /home/one/data/mysql/conf/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_pass
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=mydb
  
  slave1:
    image: 'bitnami/mysql:8.0-debian-10'
    user: root
    depends_on:
      - master
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.tag == node2
    networks:
      - one
    ports:
      - '3306'
    volumes:
      - /home/one/data/mysql/data:/bitnami/mysql/data
      - /home/one/data/mysql/slowlog:/slowlog
      - /home/one/data/mysql/conf/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_pass
      - MYSQL_MASTER_HOST=mysql_master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=rootpass

  slave2:
    image: 'bitnami/mysql:8.0-debian-10'
    user: root
    depends_on:
      - master
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.tag == node3
    networks:
      - one
    ports:
      - '3306'
    volumes:
      - /home/one/data/mysql/data:/bitnami/mysql/data
      - /home/one/data/mysql/slowlog:/slowlog
      - /home/one/data/mysql/conf/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_pass
      - MYSQL_MASTER_HOST=mysql_master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=rootpass

networks:
  one:
    external: true
    name: one-overlay

```
