### ISSUE TITLE
"[Note] Got packets out of order" is constantly showing in "stdout" logs

### ISSUE THREAD

**Issue by yuniet87** [bitnami/bitnami-docker-mysql#122]
**Description**

When I use `docker-compose` to deploy a container from the image, got this constantly:

![{E1EEF675-10C8-4A8D-9D57-B0F6060FD628}](https://user-images.githubusercontent.com/50919882/104650433-2e74a400-5684-11eb-8090-be2e3b210fb1.png)

**Steps to reproduce the issue:**

1. Create the `docker-compose` file. 
This is how mine look like
```yaml
version: '2.1'

services:
  mysql-am:
    image: 'bitnami/mysql:5.7.32'
    ports:
      - '3307:3306'
    volumes:
      - '/c/docker-vol/mysql-am-conf/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf'
      - '/c/docker-vol/mysql-am-persistence:/bitnami/mysql/data'
      - '/c/docker-vol/mysql-am-conf/2-am.sql:/docker-entrypoint-initdb.d/2-am.sql'
      - '/c/docker-vol/mysql-am-conf/3-shared.sql:/docker-entrypoint-initdb.d/3-shared.sql'
      - '/c/docker-vol/mysql-am-conf/4-analytics.sql:/docker-entrypoint-initdb.d/4-analytics.sql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MYSQL_ROOT_PASSWORD=Pa55w0rd
      - MYSQL_USER=wso2carbon
      - MYSQL_PASSWORD=Pa55w0rd
      - TZ=America/Havana
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
```
2. Execute `docker-compose up`

**Describe the results you received:**

The result is what I showed in the previous image.

**Describe the results you expected:**

That notification shouldn't be showing constantly

**Additional information you seem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 14
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 2.924GiB
 Name: docker-desktop
 ID: W2JG:VL5E:DXHC:3ORK:OHD2:EVJ7:2O6L:RNL5:Y7UY:YLKD:G4KM:M4EU
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 35
  Goroutines: 53
  System Time: 2021-01-14T21:37:44.499526898Z
  EventsListeners: 4
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.2, build 698e2846
docker-py version: 4.1.0
CPython version: 2.7.16
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
All previous `docker` and `docker-compose` is store in Docker Desktop Community for Windows 10 version: 2.2.0.0
