### ISSUE TITLE
Permission denied while cleaning data directory during container initialization

### ISSUE THREAD

**Issue by aszenz** [bitnami/bitnami-docker-mysql#123]
Permission denied error when starting mysql with existing docker named volume

**Container debug logs**  
```
mysql 07:31:41.67 
mysql 07:31:41.67 Welcome to the Bitnami mysql container
mysql 07:31:41.67 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql 07:31:41.67 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql 07:31:41.67 
mysql 07:31:41.67 INFO  ==> ** Starting MySQL setup **
mysql 07:31:41.70 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 07:31:41.70 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mysql 07:31:41.70 INFO  ==> Initializing mysql database
mysql 07:31:41.70 DEBUG ==> Ensuring expected directories/files exist
mysql 07:31:41.71 INFO  ==> Updating 'my.cnf' with custom configuration
mysql 07:31:41.72 DEBUG ==> Injecting custom configuration from my_custom.conf
mysql 07:31:41.72 INFO  ==> Injecting custom configuration 'my_custom.cnf'
mysql 07:31:41.72 DEBUG ==> Cleaning data directory to ensure successfully initialization
rm: cannot remove '/bitnami/mysql/data/*': Permission denied
```

**Compose file run via `docker-compose up -d --no-recreate`**
```
version: "3.3"

services:
  mysql:
    image: bitnami/mysql:8.0.23
    volumes:
      - 'db_data:/bitnami/mysql/data'
      - ./docs/files/qt-mysql.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      BITNAMI_DEBUG: "true"
    ports:
      - 3306:3306
    network_mode: "host"
    healthcheck:
      test: bash -c "[ -f /bitnami/mysql/.mysql_initialized ]" && mysql -uroot --silent --execute "SHOW TABLES;"

volumes:
  db_data: {}
```

**Docker version**
```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
**Docker info** 
```
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 55
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-65-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.52GiB
 Name: hpelite
 ID: MGNO:Z3LY:3GUH:3I5A:3G2B:OQAH:YNTM:ID3Y:K5OV:62K2:BI4C:HQDJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
