### ISSUE TITLE
Unable to change the value of MySQL's system variable log_slave_updates in a slave container

### ISSUE THREAD

**Issue by Houtaro** [bitnami/bitnami-docker-mysql#127]
**Description:**

I'm trying to create a slave container with the ```log_slave_updates``` disabled, so I can promote this slave to a master in the future, but when I set a custom configuration to disable the ```log_slave_updates```, it does not seem to work.

[This](https://dev.mysql.com/doc/refman/5.7/en/replication-solutions-switch.html) is the guide I was following.

**Steps to reproduce the issue:**

1. Create a ```docker-compose.yml``` file with a master & slave configuration.
2. In the ```slave``` configuration, mount a custom ```my_custom.cnf``` file in ```/opt/bitnami/mysql/conf/my_custom.cnf```
3. Inside the ```my_custom.cnf``` file, add these lines:
```
[mysqld]
log_slave_updates=0
```
4. Run the ```docker-compose.yml``` by executing the command: ```docker-compose up -d```
5. When both containers are up, go inside the ```slave``` container: ```docker exec -it <slave_container_name> bash```
6. Login to MySQL: ```mysql -u root -p``` and enter the password.
7.  Run this query to check the value of ```log_slave_updates``` variable:
```
SHOW VARIABLES LIKE "%log_slave_updates%";
```

**Received Result:**

The ```log_slave_updates``` variable is still ```ON``` as seen on this image:

![log_slave_updates_on](https://user-images.githubusercontent.com/24322960/116043456-435ccc80-a6a2-11eb-9cc5-578f4bf3e709.png)

**Expected Result:**

The ```log_slave_updates``` variable shoud be set to ```OFF```.

**Additional information you deem important (e.g. issue happens only occasionally):**

It works if the container's ```MYSQL_REPLICATION_MODE``` is ```master```.

**Output of ```docker version```:**

![docker-version](https://user-images.githubusercontent.com/24322960/116044582-ac910f80-a6a3-11eb-90ed-a71415e6015c.png)

**Output of ```docker info```:**

![docker-info](https://user-images.githubusercontent.com/24322960/116044812-efeb7e00-a6a3-11eb-9686-0e7ecb6e7299.png)

**Output of ```docker-compose version```:**

![docker-compose-version](https://user-images.githubusercontent.com/24322960/116044964-20331c80-a6a4-11eb-8420-053984e06213.png)

**Additional environment details:**

![os-release](https://user-images.githubusercontent.com/24322960/116045127-4f498e00-a6a4-11eb-93d7-93af29f40096.png)

**Comment by Mauraza** [comment]
Hi @Houtaro,

could you share your docker-compose.yaml?

**Comment by Houtaro** [comment]
Here is my ```docker-compose.yml``` file for slave container:
```
version: '2.3'
services:
  test-slave:
    image: 'bitnami/mysql:5.7'
    container_name: "test_slave"
    restart: always
    ports:
      - 3321:3306
    volumes:
      - ./conf/my_custom.cnf:/opt/bitnami/mysql/conf/bitnami/my_custom.cnf
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=test-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=testdb
      - MYSQL_ROOT_PASSWORD=testdb
    networks:
      - test_network

networks:
  test_network:
    external: true
```


Here is my ```docker-compose.yml``` for master container:
```
services:
  test-master:
    image: 'bitnami/mysql:5.7'
    container_name: "test_master"
    restart: always
    ports:
      - 3320:3306
    volumes:
      - ./conf/my_custom.cnf:/opt/bitnami/mysql/conf/bitnami/my_custom.cnf
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_ROOT_PASSWORD=testdb
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=sampledb
    networks:
      - test_network

networks:
  test_network:
    external: true
```

It can be on one ```yml``` file only, but I separated them just to simulate the scenario of separating them on different servers.
