### ISSUE TITLE
Root password not set for replica.  Access denied for user 'root'@'127.0.0.1' (using password: YES)

### ISSUE THREAD

**Issue by serg-bs** [bitnami/bitnami-docker-mysql#128]
**Description**

When copy data from official mysql docker image or restore data with percona, root password on replica not set.

**Steps to reproduce the issue:**
My docker-compose.yaml
```
version: '2.1'

services:
  mysql-master:
    image: bitnami/mysql:5.7.21
    ports:
      - 3306:3306
    volumes:
      - '/opt/mydata:/bitnami/mysql/data'
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=replicator
      - MYSQL_REPLICATION_PASSWORD=root
      - MYSQL_USER=ebbg
      - MYSQL_DATABASE=ebbg
      - MYSQL_PASSWORD=ebbgpwd
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  mysql-slave:
    image: bitnami/mysql:5.7.21
    ports:
      - 3307:3306
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=replicator
      - MYSQL_REPLICATION_PASSWORD=root
      - MYSQL_USER=ebbg
      - MYSQL_DATABASE=ebbg
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=root

    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
```

1. I copy data from Mysql official image, to /opt/mydata, alternatively resore backup using percona xtrabackup
2. Run docker-compose up

**Describe the results you received:**

1. Replication start, but root user on replica have no password configured. 
2. When I try connect I get I get error  Access denied for user 'root'@'172.24.0.1' (using password: YES)

**Describe the results you expected:**

When I run with empty data dir on primary. Root password is successefully create on replica. I excpect same result with prefilled database.

**Additional information you deem important (e.g. issue happens only occasionally):**
Look like initial script to create root password not working on replica.

**Version**
Tested on 5.7.33, 5.7.21
