### ISSUE TITLE
Unable to lock ./ibdata1 error: 11

### ISSUE THREAD

**Issue by EdanBrooke** [bitnami/bitnami-docker-mysql#129]
Hi everyone,

I am seeing `Unable to lock ./ibdata1 error: 11` on `bitnami/mysql:8.0.23-debian-10-r79`.

The permissions on the PV are as follows:
Owner: `1001`
Group: `1001`

The file permissions within the `data` directory vary. (Redacted username and group, but it's 1001:1001 as mentioned).
![image](https://user-images.githubusercontent.com/17439456/116759451-43462f00-aa0a-11eb-9caa-de477bc7e5ad.png)

My PV provider is Longhorn.

It's worth noting that after a few instances of the error message the process continues to start up and it works OK.
However, it's slowing down the start-up significantly and I want to fix it.

Kind regards
Edan

_Originally posted by @EdanBrooke in https://github.com/bitnami/bitnami-docker-mysql/issues/124#issuecomment-830430546_

**Comment by juan131** [comment]
Hi @EdanBrooke 

Thanks for opening the issue!

A couple of questions:

- Are you using the [Bitnami MySQL Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/mysql) to deploy MySQL?
- Could you share the SecurityContext you're using in your MySQL pod?

**Comment by EdanBrooke** [comment]
> Hi @EdanBrooke
> 
> Thanks for opening the issue!
> 
> A couple of questions:
> 
> * Are you using the [Bitnami MySQL Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/mysql) to deploy MySQL?
> * Could you share the SecurityContext you're using in your MySQL pod?

Hey Juan!

Yes, I am using the Bitnami MySQL Helm Chart with the following values.yaml:
```yaml
# mysql.yaml
# MySQL deployment

# Values file to use with chart https://github.com/bitnami/charts/tree/master/bitnami/mysql

architecture: standalone
clusterDomain: <redacted>

image:
  tag: 8.0.23-debian-10-r79
  debug: true

auth:
  enabled: true
  rootPassword: <redacted>

service:
  type: ClusterIP
  port: 3306

primary:
  persistence:
    enabled: true
    storageClass: longhorn
    size: 25Gi
  resources:
    requests:
      memory: 2048M
      cpu: 250m
    limits:
      memory: 4096M
      cpu: 1000m

  # Primary pod health check configuration (experimental)
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 5
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
    successThreshold: 1

# First time DB seeding for web services
initdbScripts:
  <redacted>.sql: |
    CREATE DATABASE IF NOT EXISTS file_box;
    CREATE USER IF NOT EXISTS '<redacted>'@'%' IDENTIFIED BY '<redacted>';
    GRANT ALL PRIVILEGES ON <redacted>.* TO '<redacted>'@'%';
```

I don't have any security contexts configured so it's running in the default context.

Many thanks
Edan

**Comment by juan131** [comment]
Thanks for providing all the details @EdanBrooke 

As fair as I know (by reading Longhorn docs), this kind of PVs are totally compatible with adapting the filesystem ownership using `spec.template.spec.securityContext.fsGroup` (as the MySQL chart does). So, apparently I don't see any reason why that could be the source of the problem.

In any case, could you upgrade your release setting the parameter `volumePermissions.enabled` to `true`? That should create a init container that adapts the permissions in the data volume.

**Comment by EdanBrooke** [comment]
Hi @juan131 , thanks for the tip. I've applied this change as well as:
```yaml
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
```

However, the `volume-permissions` container runs to completion (with no log output) and the MySQL container still has the same problems. Please see the logs below:
```
2021-05-04T18:27:39.897930Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2021-05-04T18:27:39.898224Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2021-05-04T18:27:39.932314Z 0 [System] [MY-010931] [Server] /opt/bitnami/mysql/bin/mysqld: ready for connections. Version: '8.0.23' socket: '/opt/bitnami/mysql/tmp/mysql.sock' port: 3306 Source distribution.
mysql 18:27:41.52 INFO ==> Stopping mysql
2021-05-04T18:27:41.525577Z 0 [System] [MY-013172] [Server] Received SHUTDOWN from user <via user signal>. Shutting down mysqld (Version: 8.0.23).
mysql 18:27:51.53 INFO ==> Stopping mysql
mysql 18:28:01.55 INFO ==> ** MySQL setup finished! **

mysql 18:28:01.57 INFO ==> ** Starting MySQL **
2021-05-04T18:28:01.779813Z 0 [System] [MY-010116] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.0.23) starting as process 1
2021-05-04T18:28:01.780913Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
2021-05-04T18:28:01.780921Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
2021-05-04T18:28:01.803308Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2021-05-04T18:28:01.819012Z 1 [ERROR] [MY-012574] [InnoDB] Unable to lock ./ibdata1 error: 11
2021-05-04T18:28:02.819496Z 1 [ERROR] [MY-012574] [InnoDB] Unable to lock ./ibdata1 error: 11
2021-05-04T18:28:03.819813Z 1 [ERROR] [MY-012574] [InnoDB] Unable to lock ./ibdata1 error: 11
2021-05-04T18:28:04.820249Z 1 [ERROR] [MY-012574] [InnoDB] Unable to lock ./ibdata1 error: 11
2021-05-04T18:28:05.820658Z 1 [ERROR] [MY-012574] [InnoDB] Unable to lock ./ibdata1 error: 11
2021-05-04T18:28:06.821084Z 1 [ERROR] [MY-012574] [InnoDB] Unable to lock ./ibdata1 error: 11
2021-05-04T18:28:07.822202Z 1 [ERROR] [MY-012574] [InnoDB] Unable to lock ./#ib_16384_0.dblwr error: 11
2021-05-04T18:28:07.822494Z 1 [ERROR] [MY-013538] [InnoDB] Doublewrite file create failed: ./#ib_16384_0.dblwr
2021-05-04T18:28:07.822661Z 1 [ERROR] [MY-012930] [InnoDB] Plugin initialization aborted with error I/O error.
2021-05-04T18:28:08.089358Z 0 [System] [MY-010910] [Server] /opt/bitnami/mysql/bin/mysqld: Shutdown complete (mysqld 8.0.23) Source distribution.
2021-05-04T18:28:08.319904Z 1 [ERROR] [MY-010334] [Server] Failed to initialize DD Storage Engine
2021-05-04T18:28:08.320213Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2021-05-04T18:28:08.320542Z 0 [ERROR] [MY-010119] [Server] Aborting
2021-05-04T18:28:08.321066Z 0 [System] [MY-010910] [Server] /opt/bitnami/mysql/bin/mysqld: Shutdown complete (mysqld 8.0.23) Source distribution.
```

This is certainly a strange one to me.
Any help in solving this would really be appreciated 🤞

Thank you
Edan

**Comment by juan131** [comment]
That's so weird @EdanBrooke 

Are you reusing an exiting PVC (setting `primary.persistence.existingClaim` property) or sth like that?
Do you have the same PVC used in the MySQL pod attached to another pod? That error usually happens when there's a second process locking the Innodb data file.

**Comment by EdanBrooke** [comment]
I've tried deleting the PV and allowing it to re-create it but this hasn't helped. I'm not specifying any existing claim.
It's only used on the MySQL pod and has ReadWriteOnce set.

Is there any way to debug what's actually locking the file do you think, @juan131 ?
I have uninstalled the Helm release, purged all PVs/PVCs and re-installed to no avail. :(

**Comment by juan131** [comment]
Hi @EdanBrooke 

I think the problem could be related with MySQL not liberating the `./ibdata1` during the initialization. Let me give some context:

---

Our container follows this flow:

- The [entrypoint](https://github.com/bitnami/bitnami-docker-mysql/blob/master/8.0/debian-10/rootfs/opt/bitnami/scripts/mysql/entrypoint.sh) calls the [setup.sh](https://github.com/bitnami/bitnami-docker-mysql/blob/master/8.0/debian-10/rootfs/opt/bitnami/scripts/mysql/setup.sh) script that configure MySQL based on env. variables.
- Once the setup.sh finishes, it calls the [run.sh](https://github.com/bitnami/bitnami-docker-mysql/blob/master/8.0/debian-10/rootfs/opt/bitnami/scripts/mysql/run.sh) script that starts MySQL.

During the "setup", the function [mysql_initialize](https://github.com/bitnami/bitnami-docker-mysql/blob/master/8.0/debian-10/rootfs/opt/bitnami/scripts/libmysql.sh#L247) is invoked. This function starts MySQL in background to create the default users and so on, see:

- https://github.com/bitnami/bitnami-docker-mysql/blob/master/8.0/debian-10/rootfs/opt/bitnami/scripts/libmysql.sh#L287

At the end on the "setup", the background MySQL process is stopped, see:

- https://github.com/bitnami/bitnami-docker-mysql/blob/master/8.0/debian-10/rootfs/opt/bitnami/scripts/mysql/setup.sh#L36

---

With this context in mind, I think it could be possible the background MySQL process is not liberating `./ibdata1` properly. I mean, we might need to wait some seconds before starting MySQL in the **run.sh** script to ensure that `./ibdata1` is not locked.

To test this, you can try installing the chart adding the block below to your values that overwrites the default entrypoint:

```yaml
primary:
  command:
    - /bin/bash
    - ec
    - |
      # Load libraries
      . /opt/bitnami/scripts/libbitnami.sh
      . /opt/bitnami/scripts/libmysql.sh
      # Load MySQL environment variables
      . /opt/bitnami/scripts/mysql-env.sh

      print_welcome_page
      if [[ "$1" = "/opt/bitnami/scripts/mysql/run.sh" ]]; then
           info "** Starting MySQL setup **"
           /opt/bitnami/scripts/mysql/setup.sh
           info "** MySQL setup finished! **"
      fi
      echo ""
      sleep 20
      exec "$@"
```

> Please note that I added a "sleep 20" command to wait some seconds before starting MySQL

**Comment by EdanBrooke** [comment]
> Hi @EdanBrooke
> 
> I think the problem could be related with MySQL not liberating the `./ibdata1` during the initialization. Let me give some context:
> 
> Our container follows this flow:
> 
> * The [entrypoint](https://github.com/bitnami/bitnami-docker-mysql/blob/master/8.0/debian-10/rootfs/opt/bitnami/scripts/mysql/entrypoint.sh) calls the [setup.sh](https://github.com/bitnami/bitnami-docker-mysql/blob/master/8.0/debian-10/rootfs/opt/bitnami/scripts/mysql/setup.sh) script that configure MySQL based on env. variables.
> * Once the setup.sh finishes, it calls the [run.sh](https://github.com/bitnami/bitnami-docker-mysql/blob/master/8.0/debian-10/rootfs/opt/bitnami/scripts/mysql/run.sh) script that starts MySQL.
> 
> During the "setup", the function [mysql_initialize](https://github.com/bitnami/bitnami-docker-mysql/blob/master/8.0/debian-10/rootfs/opt/bitnami/scripts/libmysql.sh#L247) is invoked. This function starts MySQL in background to create the default users and so on, see:
> 
> * https://github.com/bitnami/bitnami-docker-mysql/blob/master/8.0/debian-10/rootfs/opt/bitnami/scripts/libmysql.sh#L287
> 
> At the end on the "setup", the background MySQL process is stopped, see:
> 
> * https://github.com/bitnami/bitnami-docker-mysql/blob/master/8.0/debian-10/rootfs/opt/bitnami/scripts/mysql/setup.sh#L36
> 
> With this context in mind, I think it could be possible the background MySQL process is not liberating `./ibdata1` properly. I mean, we might need to wait some seconds before starting MySQL in the **run.sh** script to ensure that `./ibdata1` is not locked.
> 
> To test this, you can try installing the chart adding the block below to your values that overwrites the default entrypoint:
> 
> ```yaml
> primary:
>   command:
>     - /bin/bash
>     - ec
>     - |
>       # Load libraries
>       . /opt/bitnami/scripts/libbitnami.sh
>       . /opt/bitnami/scripts/libmysql.sh
>       # Load MySQL environment variables
>       . /opt/bitnami/scripts/mysql-env.sh
> 
>       print_welcome_page
>       if [[ "$1" = "/opt/bitnami/scripts/mysql/run.sh" ]]; then
>            info "** Starting MySQL setup **"
>            /opt/bitnami/scripts/mysql/setup.sh
>            info "** MySQL setup finished! **"
>       fi
>       echo ""
>       sleep 20
>       exec "$@"
> ```
> 
> > Please note that I added a "sleep 20" command to wait some seconds before starting MySQL

Cheers, I'll give it a try tonight and feed back.

Edan

**Comment by juan131** [comment]
Hi @EdanBrooke  

> I am seeing the following with this config:
> ```
> /bin/bash: ec: No such file or directory
> ```

Sorry there was a typo. It's easy to fix by applying the change below:

```diff
primary:
  command:
    - /bin/bash
-   - ec
+   - -ec
    - |
...
```

---

The alternative you took (building a custom image) should work too!

> However, whilst the server does seem to start eventually it's still trying to perform an upgrade every time unnecessarily and the start-up therefore takes 2.5 minutes which is a little too long in my eyes

Correct, MySQL schemas are upgraded everytime the container is initialized, see:

- https://github.com/bitnami/bitnami-docker-mysql/blob/master/8.0/debian-10/rootfs/opt/bitnami/scripts/libmysql.sh#L281

On container restarts, I agree it could be unnecessary to do perform this step. However, you cant' distinguish between the container simply restarting (e.g. because the pod was reallocated) or the container replaced by a new version as part of a deployment update process. In case you're upgrading MySQL (e.g. replacing `8.0.23` image with `8.0.24`) this step is mandatory to ensure the schema is compatible.

**Comment by EdanBrooke** [comment]
So, just tried to switch to the `command` parameter you provided @juan131 , but I see this and the pod goes into CrashLoopBackOff.
```
/bin/bash: line 1: ./opt/bitnami/scripts/libbitnami.sh: Permission denied
/bin/bash: line 1: ./opt/bitnami/scripts/libbitnami.sh: Permission denied
/bin/bash: line 1: ./opt/bitnami/scripts/libbitnami.sh: Permission denied
```

My config is as follows:
```yaml

primary:
  command:
    - /bin/bash
    - -ec
    - |
      # Load libraries
      ./opt/bitnami/scripts/libbitnami.sh
      ./opt/bitnami/scripts/libmysql.sh
      # Load MySQL environment variables
      ./opt/bitnami/scripts/mysql-env.sh

      print_welcome_page
      if [[ "$1" = "/opt/bitnami/scripts/mysql/run.sh" ]]; then
           info "** Starting MySQL setup **"
           /opt/bitnami/scripts/mysql/setup.sh
           info "** MySQL setup finished! **"
      fi
      echo ""
      sleep 20
      exec "$@"
```

**Comment by juan131** [comment]
Hi @EdanBrooke 

It seems you remove some mandatory spaces when copy-pasting my suggestion. Please apply the changes below so they are included:

```diff
primary:
  command:
    - /bin/bash
    - -ec
    - |
      # Load libraries
-     ./opt/bitnami/scripts/libbitnami.sh
+     . /opt/bitnami/scripts/libbitnami.sh
-     ./opt/bitnami/scripts/libmysql.sh
+     . /opt/bitnami/scripts/libmysql.sh
      # Load MySQL environment variables
-     ./opt/bitnami/scripts/mysql-env.sh
+     . /opt/bitnami/scripts/mysql-env.sh

      print_welcome_page
      if [[ "$1" = "/opt/bitnami/scripts/mysql/run.sh" ]]; then
           info "** Starting MySQL setup **"
           /opt/bitnami/scripts/mysql/setup.sh
           info "** MySQL setup finished! **"
      fi
      echo ""
      sleep 20
      exec "$@"
 ```
 
 >  is it necessary for a change to be made upstream to check if the ibdata file is locked to remove the need for this workaround?

We'll have to improve the `mysqld_stop` function so it wait both for the MySQL process to be stopped, and the resources to be unlocked.

**Comment by EdanBrooke** [comment]
> Hi @EdanBrooke
> 
> It seems you remove some mandatory spaces when copy-pasting my suggestion. Please apply the changes below so they are included:
> 
> ```diff
> primary:
>   command:
>     - /bin/bash
>     - -ec
>     - |
>       # Load libraries
> -     ./opt/bitnami/scripts/libbitnami.sh
> +     . /opt/bitnami/scripts/libbitnami.sh
> -     ./opt/bitnami/scripts/libmysql.sh
> +     . /opt/bitnami/scripts/libmysql.sh
>       # Load MySQL environment variables
> -     ./opt/bitnami/scripts/mysql-env.sh
> +     . /opt/bitnami/scripts/mysql-env.sh
> 
>       print_welcome_page
>       if [[ "$1" = "/opt/bitnami/scripts/mysql/run.sh" ]]; then
>            info "** Starting MySQL setup **"
>            /opt/bitnami/scripts/mysql/setup.sh
>            info "** MySQL setup finished! **"
>       fi
>       echo ""
>       sleep 20
>       exec "$@"
> ```
> 
> > is it necessary for a change to be made upstream to check if the ibdata file is locked to remove the need for this workaround?
> 
> We'll have to improve the `mysqld_stop` function so it wait both for the MySQL process to be stopped, and the resources to be unlocked.

Evening @juan131,

I have applied this now and the welcome message prints OK but then the pod terminates (exit code `0`) and goes into CrashLoopBackOff.
Log output:
```
mysql 18:42:02.22
mysql 18:42:02.22 Welcome to the Bitnami mysql container
mysql 18:42:02.22 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql 18:42:02.22 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql 18:42:02.22
```

Thank you
Edan

**Comment by juan131** [comment]
Hi @juan131 

That's weird.. You're not overwriting the `primary.args` parameter right? Try with these yaml:

```yaml
primary:
  command:
    - /bin/bash
    - -ec
    - |
      # Load libraries
      . /opt/bitnami/scripts/libbitnami.sh
      . /opt/bitnami/scripts/libmysql.sh
      # Load MySQL environment variables
      . /opt/bitnami/scripts/mysql-env.sh

      print_welcome_page

      info "** Starting MySQL setup **"
      /opt/bitnami/scripts/mysql/setup.sh
      info "** MySQL setup finished! **"

      echo ""
      sleep 20
      exec /opt/bitnami/scripts/mysql/run.sh
```

**Comment by EdanBrooke** [comment]
> Hi @juan131
> 
> That's weird.. You're not overwriting the `primary.args` parameter right? Try with these yaml:
> 
> ```yaml
> primary:
>   command:
>     - /bin/bash
>     - -ec
>     - |
>       # Load libraries
>       . /opt/bitnami/scripts/libbitnami.sh
>       . /opt/bitnami/scripts/libmysql.sh
>       # Load MySQL environment variables
>       . /opt/bitnami/scripts/mysql-env.sh
> 
>       print_welcome_page
> 
>       info "** Starting MySQL setup **"
>       /opt/bitnami/scripts/mysql/setup.sh
>       info "** MySQL setup finished! **"
> 
>       echo ""
>       sleep 20
>       exec /opt/bitnami/scripts/mysql/run.sh
> ```

Hi @juan131 ,

No, I'm not overriding the `args` parameter.
However, with the YAML you provided the pod seems to start correctly and at least so far I'm not seeing `./ibdata1 error: 11` error.

I guess now we need to validate that this was indeed the issue and have someone kindly make the required changes?

Thank you!
Edan

**Comment by juan131** [comment]
hi @EdanBrooke 

I just created a PR that attempts to improve this. I published an image in DockerHub for you to test it with these changes, you can give it a try by installing the chart with the values.yaml below:

```yaml
image:
  repository: juanariza131/mysql
  tag: 8.0
```

**Comment by EdanBrooke** [comment]
> hi @EdanBrooke
> 
> I just created a PR that attempts to improve this. I published an image in DockerHub for you to test it with these changes, you can give it a try by installing the chart with the values.yaml below:
> 
> ```yaml
> image:
>   repository: juanariza131/mysql
>   tag: 8.0
> ```

Hey Juan!

Seems to work, so the PR should fix my issue thank you.

Of course, the tag should probably be `tag: "8.0"` else the YAML parser will convert it to an integer `8` and you will see ImagePullBackOff errors for it.

The issue raised used to happen almost always and I haven't been able to re-produce it yet with this image or with the command override you provided previously. In fact, I am seeing `Waiting for mysql to unlock db files` with your image, and the server starts a few moments later so definitely seems good!

Thank you very much for your help @juan131 and have a good one. 🎉

Kind regards,
Edan

**Comment by juan131** [comment]
@EdanBrooke we're working on a new release of the MySQL images including the changes I proposed in the PR. I'll keep you updated and let you know it when the containers are published.

**Comment by juan131** [comment]
The image revision `8.0.25-debian-10-r5` was just released @EdanBrooke . Could you give it a try?

**Comment by EdanBrooke** [comment]
Hi Juan,

Just tried this now, MySQL upgrades as expected and then restarts and then voila! Container is up and ready to accept connections. 

Thank you @juan131 for all of your work on this. I am very impressed with your swift resolution and helpful responses, especially given this is a free open source project! Kudos to you and thanks once again. I can now finally crack on with building my app.

FYI to anyone reading in the future, my Helm values YAML now looks like this:
(I kept the volume permissions init container enabled for safety. It only impacts the start-up time which I don't particularly care about.)
```yaml
# mysql.yaml
# MySQL deployment

# Values file to use with chart https://github.com/bitnami/charts/tree/master/bitnami/mysql

architecture: standalone
clusterDomain: my.cluster.internal

# Image options for bitnami/mysql
image:
  # Version pinned image, update as necessary
  tag: 8.0.25-debian-10-r5
auth:
  enabled: true
  rootPassword: supersecret

# Service configuration
service:
  type: ClusterIP
  port: 3306

volumePermissions:
  enabled: true
  
primary:
  # PV configuration for primary pod
  persistence:
    enabled: true
    storageClass: longhorn
    size: 25Gi

  # Resource limits for primary pod
  resources:
    requests:
      memory: 2048M
      cpu: 250m
    limits:
      memory: 4096M
      cpu: 1000m

  # Primary pod node selectors
  nodeSelector:
    systemtype: dedicated

  # Primary pod health check configuration (experimental)
  # Liveness probe will restart the pod upon failure. Readiness probe stops the pod from responding to traffic until it becomes ready.
  livenessProbe:
    enabled: true
    initialDelaySeconds: 150
    periodSeconds: 15
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 15
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

# First time DB seeding for web services
initdbScripts:
  seed.sql: |
    CREATE DATABASE IF NOT EXISTS seed;
    CREATE USER IF NOT EXISTS 'seed'@'%' IDENTIFIED BY 'mysecret';
    GRANT ALL PRIVILEGES ON seed.* TO 'seed'@'%';
```

Best wishes,
Edan
