### ISSUE TITLE
Mysql docker container always restart

### ISSUE THREAD

**Issue by Informaticaucu** [bitnami/bitnami-docker-mysql#133]
My docker-compose.yml file

```yaml
version: '2'
services:
  mysqldb:
    image: bitnami/mysql:5.7
    restart: always
    volumes:
      - '/data/mysqldb_data:/bitnami/mysql/data'
    environment:
      - MYSQL_USER=webmaster
      - MYSQL_PASSWORD=Webmaster_135
      - MYSQL_DATABASE=wpucudb
      - MYSQL_ROOT_PASSWORD=root911
  wordpress:
    image: docker.io/bitnami/wordpress:5
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - '/data/wordpress_data:/bitnami/wordpress'
    depends_on:
      - mysqldb
    environment:
      - WORDPRESS_DATABASE_HOST=mysqldb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=webmaster
      - WORDPRESS_DATABASE_PASSWORD=Webmaster_135
      - WORDPRESS_DATABASE_NAME=wpucudb
volumes:
  mysqldb_data:
    driver: local
  wordpress_data:
    driver: local
```

**Comment by Informaticaucu** [comment]
mysql 20:59:40.14 Welcome to the Bitnami mysql container
mysql 20:59:40.14 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql 20:59:40.14 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql 20:59:40.15 
mysql 20:59:40.15 INFO  ==> ** Starting MySQL setup **
mysql 20:59:40.17 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 20:59:40.17 INFO  ==> Initializing mysql database
mysql 20:59:40.18 INFO  ==> Updating 'my.cnf' with custom configuration
mysql 20:59:40.18 INFO  ==> Setting user option
mysql 20:59:40.19 INFO  ==> Installing database
mysql 21:00:40.67 
mysql 21:00:40.67 Welcome to the Bitnami mysql container
mysql 21:00:40.67 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql 21:00:40.67 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql 21:00:40.67 
mysql 21:00:40.67 INFO  ==> ** Starting MySQL setup **
mysql 21:00:40.69 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 21:00:40.70 INFO  ==> Initializing mysql database
mysql 21:00:40.71 INFO  ==> Updating 'my.cnf' with custom configuration
mysql 21:00:40.71 INFO  ==> Setting user option
mysql 21:00:40.72 INFO  ==> Installing database
mysql 21:01:41.25 
mysql 21:01:41.25 Welcome to the Bitnami mysql container
mysql 21:01:41.25 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql 21:01:41.25 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql 21:01:41.25 
mysql 21:01:41.25 INFO  ==> ** Starting MySQL setup **
mysql 21:01:41.27 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 21:01:41.28 INFO  ==> Initializing mysql database
mysql 21:01:41.29 INFO  ==> Updating 'my.cnf' with custom configuration
mysql 21:01:41.29 INFO  ==> Setting user option
mysql 21:01:41.30 INFO  ==> Installing database
root@testpag:/data#

**Comment by juan131** [comment]
Hi @Informaticaucu 

There's something that's failing during the installation of the database. Could you please add the env. variable `BITNAMI_DEBUG=true` to MySQL so we obtain more info in the logs?

```diff
(...)
  mysqldb:
    (...)
    environment:
      (...)
      - MYSQL_ROOT_PASSWORD=root911
+     - BITNAMI_DEBUG=true
  (...)
```

---

Apart from that, I noticed that you're creating Docker volumes, see:

```yaml
volumes:
  mysqldb_data:
    driver: local
  wordpress_data:
    driver: local
```

But you're not using them.. Instead you're mounting a directories directly from the host:

```yaml
(...)
    volumes:
      - '/data/mysqldb_data:/bitnami/mysql/data'
    (...)
    volumes:
      - '/data/wordpress_data:/bitnami/wordpress'
(...)
```

Could you explain why are you doing so?
