### ISSUE TITLE
 Problem running mysql and apache yml files  

### ISSUE THREAD

**Issue by shayc12** [bitnami/bitnami-docker-mysql#46]
Hello,

I try to run mysql and apache from yml file:
my YML file:

```
services:
  apacheweb:
    image: "apache:dockerfile"
    container_name: apache_srv
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./tmp_data/apache-data:/app
    environment:
      - APACHE_HTTPS_PORT_NUMBER="443"
      - APACHE_HTTP_PORT_NUMBER="80"
      - BITNAMI_APP_NAME="apache"
      - BITNAMI_IMAGE_VERSION="2.4.29-r3"
      - PATH="/opt/bitnami/apache/bin:$PATH"
  databasesql:
    image: "mysql:dockerfile"
    container_name: mysql_srv
    labels:
      kompose.service.type: nodeport-mysql
    ports:
      - '3306:3306'
    volumes:
      - ./tmp_data/mysql-data:/bitnami

    #dir path of dbs : /bitnami/mysql/data
    environment:
      - ALLOW_EMPTY_PASSWORD="no"
      - BITNAMI_APP_NAME="mysql"
      - BITNAMI_IMAGE_VERSION="5.7.21-r1"
      - MYSQL_DATABASE="testdb"
      - MYSQL_MASTER_HOST=""
      - MYSQL_MASTER_PORT_NUMBER=""
      - MYSQL_MASTER_ROOT_PASSWORD=""
      - MYSQL_MASTER_ROOT_USER=""
      - MYSQL_PASSWORD="admin"
      - MYSQL_PORT_NUMBER="3306"
      - MYSQL_REPLICATION_MODE=""
      - MYSQL_REPLICATION_PASSWORD=""
      - MYSQL_REPLICATION_USER=""
      - PATH="/opt/bitnami/mysql/bin:/opt/bitnami/mysql/sbin:$PATH"
```

i receive those errors when i try to login to those container:

```
Welcome to the Bitnami "mysql" container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-"mysql"
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-"mysql"/issues
Send us your feedback at containers@bitnami.com

/opt/bitnami/base/helpers: line 15: nami: command not found
/opt/bitnami/base/helpers: line 15: grep: command not found
INFO ==> Starting mysql...
[FATAL tini (12)] exec nami failed: No such file or directory

Welcome to the Bitnami "apache" container
Subscribe to project updates by watching 
Submit issues and feature requests at 
Send us your feedback at containers@bitnami.com

/opt/bitnami/base/helpers: line 15: grep: command not found
/opt/bitnami/base/helpers: line 15: nami: command not found
INFO ==> Starting apache...
/init.sh: line 6: nami: command not found
```

Any idea?
