### ISSUE TITLE
mysql not starting on second run

### ISSUE THREAD

**Issue by rajali** [bitnami/bitnami-docker-mysql#47]
**Description**
MySQL failings to run  while using persistence data

I am running this image : 'bitnami/mysql:5.7.23-debian-9-r23'
- Data is being persisted to a local folder
- On first run through docker-compose the server is able to run and I can use it to populate schema and data.

**Steps to reproduce the issue:**
Docker-compose file to use:
```
version: '3'

services:

  mysql:
    image: 'bitnami/mysql:5.7.23-debian-9-r23'
    ports:
      - '3306:3306'
    restart: always
    volumes:
      # used to persist data
      - ../mysql/persistence:/bitnami
      # used to initialise the database
    environment:
     # set the root user
      - MYSQL_ROOT_USER=root
     # set the root password
      - MYSQL_ROOT_PASSWORD=password
     # creating the database at startup
      - MYSQL_DATABASE=local_database
     # create database user on first run
      - MYSQL_USER=local_database_user
     # set the database user password
      - MYSQL_PASSWORD=password
      - NAMI_DEBUG="--log-level trace"
```

1. docker-compose up
2. load some schema and data, or even without it
3. docker-compose stop MYSQL-CONTAINER-NAME
4. docker-compose rm MYSQL-CONTAINER-NAME
5. docker-compose up

```
**Describe the results you received:**
mysql_1  | nami    INFO  Initializing mysql
mysql_1  | mysql   TRACE [restorePersistedData] Restoring /bitnami/mysql/data to /opt/bitnami/mysql/data
mysql_1  | mysql   INFO 
mysql_1  | mysql   INFO  ########################################################################
mysql_1  | mysql   INFO   Installation parameters for mysql:
mysql_1  | mysql   INFO     Persisted data and properties have been restored.
mysql_1  | mysql   INFO     Any input specified will not take effect.
mysql_1  | mysql   INFO   This installation requires no credentials.
mysql_1  | mysql   INFO  ########################################################################
mysql_1  | mysql   INFO 
mysql_1  | nami    INFO  mysql successfully initialized
mysql_1  | app-entrypoint.sh 14:16:43.36 INFO  ==> Starting mysql... 
mysql_1  | run.sh 14:16:43.38 INFO  ==> Starting mysqld_safe...
mysql_1  | 2018-09-08T14:16:43.533393Z mysqld_safe error: log-error set to '/opt/bitnami/mysql/logs/mysqld.log', however file don't exists. Create writable for user 'mysql'.
docker_mysql_1 exited with code 1
```

**Describe the results you expected:**
MYSQL should not exit, and keep running.
