### ISSUE TITLE
Unable to execute custom sql files

### ISSUE THREAD

**Issue by petrandr** [bitnami/bitnami-docker-mysql#61]
**Description**
Hi to all,

My main goal is to make the slave container to be `read_only`.
While trying to do that a force an issue of executing custom sql files (`docker-entrypoint-initdb.d`)

I tried to use a custom .cnf file as described in the documentation and a manage to enable the `read_only` but the root user was able to write. So i enabled the `super_read_only`, i rebuild the container and then the replication was failing. Also i tried to enable the `innodb_read_only` but the root was still able to write.

So i decided to try a different way based on the documentation. I use the volumes to mount an `sql` file to the `/docker-entrypoint-initdb.d/` folder and then a run the following commands:

**Delete slave container and volume**
```bash
docker stop MysqlReplicaServer && docker rm MysqlReplicaServer && docker volume rm docker_mysql_slave_data
```

**Start slave container**
```bash
docker-compose up mysql.replica.dev
```
The above command was `failing` while trying to load user's custom files (see the response below). If comment out the line of which is mounting the `sql_init_custom.sql`, the container is starting successfully.

**Response**
```bash
MysqlReplicaServer               | Welcome to the Bitnami mysql container
MysqlReplicaServer               | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
MysqlReplicaServer               | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
MysqlReplicaServer               | Send us your feedback at containers@bitnami.com
MysqlReplicaServer               | 
MysqlReplicaServer               | INFO  ==> ** Starting MySQL setup **
MysqlReplicaServer               | INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
MysqlReplicaServer               | INFO  ==> Initializing mysql database...
MysqlReplicaServer               | INFO  ==> Configuration replication mode...
MysqlReplicaServer               | INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
MysqlReplicaServer               | INFO  ==> Stopping mysql...
MysqlReplicaServer exited with code 1
```
## All the files that am using for the project

**sql_init_custom.sql**
```sql
CREATE USER 'admin'@'%' IDENTIFIED WITH mysql_native_password BY '';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, FILE, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EXECUTE ON *.* TO 'admin'@'%' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
```
**my_custom.cnf**
```config
[mysqld]
read_only                 = 1
super_read_only       = 0
innodb_read_only     = 1
```

**docker-compose.yml**
```yml
## Docker Compose v3.5
version: '3.5'
services:
## Master Database Server
  mysql.master.dev:
    container_name: MysqlMasterServer
    image: 'bitnami/mysql:latest'
    ports:
      - "1306:3306"
    expose:
      - "1306"
    networks:
      - dev-env
    volumes:
      - mysql_master_data:/bitnami
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_REPLICATION_MODE: master
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_DATABASE: my_database

  ## Slave Database Server
  mysql.replica.dev:
    container_name: MysqlReplicaServer
    image: 'bitnami/mysql:latest'
    ports:
      - "1307:3306"
    expose:
      - "1307"
    volumes:
      - mysql_slave_data:/bitnami
      #- ./mysql-configs/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf
      - ./sql_init_custom.sql:/docker-entrypoint-initdb.d/sql_init_custom.sql
    networks:
      - dev-env
    depends_on:
      - mysql.master.dev
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_REPLICATION_MODE: slave
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_DATABASE: my_database
      MYSQL_MASTER_HOST: mysql.master.dev
      MYSQL_MASTER_PORT_NUMBER: 3306

## Volumes
volumes:
  mysql_master_data:
    driver: local
  mysql_slave_data:
    driver: local

## Networks
networks:
  dev-env:
    name: Infrastructure
    driver: bridge
```

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Containers: 8
 Running: 7
 Paused: 0
 Stopped: 1
Images: 39
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-43-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.47GiB
Name: unix
ID: KNRJ:RVUN:WCXV:OVU4:5URF:5LXR:XF22:DFD6:YS7H:DFYT:WCFQ:QKMV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
