### ISSUE TITLE
Master Node not starting

### ISSUE THREAD

**Issue by TachyonRSA** [bitnami/bitnami-docker-mysql#62]
**Description**

I am trying to setup a basic replication cluster with persistent storage but it would appear that the master node doesn't get setup correctly. It keeps stopping without doing anything that I can see in the logs.

**Steps to reproduce the issue:**

1. Create `docker-compose.yml`
2. Run `docker-compose up -d --build --scale master=1 --scale slave=2`

**Describe the results you received:**

> Welcome to the Bitnami mysql container
> 
> 
> Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
> 
> 
> Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
> 
> 
> Send us your feedback at containers@bitnami.com
> 
> 
> 
> 
> INFO  ==> ** Starting MySQL setup **
> 
> 
> INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
> 
> 
> INFO  ==> Initializing mysql database...
> 
> 
> INFO  ==> Stopping mysql...
> 
> 

**Describe the results you expected:**

I expected the container to be up and running and ready to use.

**Additional information you deem important (e.g. issue happens only occasionally):**

Here is the `docker-compose.yml` file:
```
version: '2'

services:
  master:
    image: 'bitnami/mysql:latest'
    ports:
      - '3306'
    volumes:
      - /docker-data/mysql/:/bitnami/mysql/data
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=vyIoazpGKRYVsojeLZRY
      - MYSQL_ROOT_PASSWORD=ShwwEJXurGeDHpohDeZI
      - MYSQL_USER=athena
      - MYSQL_PASSWORD=VpQrvGImPezzXbRrZDMC
      - MYSQL_DATABASE=athena
  slave:
    image: 'bitnami/mysql:latest'
    ports:
      - '3306'
    depends_on:
      - master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=vyIoazpGKRYVsojeLZRY
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=ShwwEJXurGeDHpohDeZI
```

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 16
 Running: 16
 Paused: 0
 Stopped: 0
Images: 172
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-42-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 15.63GiB
Name: dedicated.assorted.co.za
ID: HXYZ:ZXHI:2HZC:VF47:JKJ3:EFJY:VA2B:5STB:N5CB:ZNZB:3YYZ:2MJR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```
