### ISSUE TITLE
mysql-master_1 exited with code 1

### ISSUE THREAD

**Issue by marknguyen85** [bitnami/bitnami-docker-mysql#64]
when i used 
```
    volumes:
      - "${DATA_PATH_HOST}/mysql:/bitnami/mysql/data" 
```
for Persisting  database then throw 

```
mysql-master_1  | INFO  ==> ** Starting MySQL setup **
mysql-master_1  | INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
mysql-master_1  | INFO  ==> Initializing mysql database...
mysql-slave_1   |
mysql-slave_1   | INFO  ==> ** Starting MySQL setup **
mysql-slave_1   | INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
mysql-slave_1   | INFO  ==> Initializing mysql database...
mysql-slave_1   | INFO  ==> Configuration replication mode...
mysql-master_1  | INFO  ==> Configuration replication mode...
mysql-master_1  | INFO  ==> Stopping mysql...
mysql-master_1 exited with code 1
```

but i removed volumes and worked.

here my docker-compose code

```
version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
### MySQL ################################################
  mysql-master:
    build:
      context: ./mysql2
    ports:
      - "3306:3306"
    volumes:
      - "${DATA_PATH_HOST}/mysql:/bitnami"
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=${MYSQL_USER}
      - MYSQL_REPLICATION_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - backend

  mysql-slave:
    build:
      context: ./mysql2
    ports:
      - "3306"
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=${MYSQL_USER}
      - MYSQL_REPLICATION_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - backend
```
