### ISSUE TITLE
How to connect to slave server?

### ISSUE THREAD

**Issue by marknguyen85** [bitnami/bitnami-docker-mysql#65]
i ran 2 container about 1 master and 1 slave as below

```
b6575d11271a        mysql-slave    "/entrypoint.sh /run…"   9 minutes ago       Up 3 minutes        0.0.0.0:3307->3306/tcp   mysql-slave_1
3a4b6606404f        mysql-master   "/entrypoint.sh /run…"   9 minutes ago       Up 3 minutes        0.0.0.0:3306->3306/tcp   mysql-master_1
```
master server connected but i can not connect to slave server and throw message 

`Host '172.23.0.1' is not allowed to connect to this MySQL server`

**Comment by javsalgar** [comment]
Hi,

Could you share the docker-compose file that you used? Did you use the one in our repo?

**Comment by marknguyen85** [comment]
> Hi,
> 
> Could you share the docker-compose file that you used? Did you use the one in our repo?
yes certainly here my code 

in Dockerfile 
```
FROM bitnami/mysql:latest

LABEL maintainer="MarkNguyen"
```
and docker-compose file 
```
version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  bundle-data:

services:
### MySQL Replica################################################
    mysql-master:
      build:
        context: ./mysql2
      ports:
        - "${MYSQL_PORT}:3306"
      expose:
        - ${MYSQL_PORT}
      volumes:
        - ${DATA_PATH_HOST}/mysql-persistence:/bitnami/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_REPLICATION_MODE=master
        - MYSQL_REPLICATION_USER=${MYSQL_SLAVE_USER}
        - MYSQL_REPLICATION_PASSWORD=${MYSQL_SLAVE_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
      networks:
        - backend

    mysql-slave:
      build:
        context: ./mysql2
      ports:
        - "${MYSQL_SLAVE_PORT}:3306"
      expose:
        - ${MYSQL_SLAVE_PORT}
      depends_on:
        - mysql-master
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_REPLICATION_MODE=slave
        - MYSQL_REPLICATION_USER=${MYSQL_SLAVE_USER}
        - MYSQL_REPLICATION_PASSWORD=${MYSQL_SLAVE_PASSWORD}
        - MYSQL_MASTER_PORT_NUMBER=${MYSQL_PORT}
        - MYSQL_MASTER_HOST=mysql-master
        - MYSQL_MASTER_USER=${MYSQL_PASSWORD}
        - MYSQL_MASTER_PASSWORD=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
      networks:
        - backend
        
```
