### ISSUE TITLE
Error writing file '/opt/bitnami/mysql/tmp/MLyxoSoO' (errno: 28 - No space left on device)

### ISSUE THREAD

**Issue by marknguyen85** [bitnami/bitnami-docker-mysql#67]
i used config to run master and slave and when i try inserted datas to master then got error 

`Error Code: 1026. Error writing file '/opt/bitnami/mysql/tmp/MLyxoSoO' (errno: 28 - No space left on device)`

Plz help me. Thank alot.

**Comment by tompizmor** [comment]
The error is clear here, `No space left on device`.  You need to clean some space in the place where you have your MySQL data.

Can you let us a bit more about your deployment?

- Are you running the MySQL image in Kubernetes, locally with docker-compose, or another thing?
- What kind of volume are you using?

**Comment by marknguyen85** [comment]
> The error is clear here, `No space left on device`. You need to clean some space in the place where you have your MySQL data.
> 
> Can you let us a bit more about your deployment?
> 
> * Are you running the MySQL image in Kubernetes, locally with docker-compose, or another thing?
> * What kind of volume are you using?

i run on locally with docker-compose and docker-compose file here 
```

version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:

### MySQL Replica################################################
    mysql-master:
      build:
        context: ./mysql2
      ports:
        - "${MYSQL_PORT}:3306"
      expose:
        - ${MYSQL_PORT}
      restart: always
      volumes:
        - ${DATA_PATH_HOST}/mysql-persistence:/bitnami/mysql
        - ./mysql2/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
      environment:
        - MYSQL_REPLICATION_MODE=master
        - MYSQL_REPLICATION_USER=${MYSQL_SLAVE_USER}
        - MYSQL_REPLICATION_PASSWORD=${MYSQL_SLAVE_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      networks:
        - backend

    mysql-slave:
      build:
        context: ./mysql2
      ports:
        - "${MYSQL_PORT_SLAVE}:3306"
      volumes:
        - ./mysql2/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
      expose:
        - ${MYSQL_PORT_SLAVE}
      restart: always
      depends_on:
        - mysql-master
      environment:
        - MYSQL_REPLICATION_MODE=slave
        - MYSQL_REPLICATION_USER=${MYSQL_SLAVE_USER}
        - MYSQL_REPLICATION_PASSWORD=${MYSQL_SLAVE_PASSWORD}
        - MYSQL_MASTER_PORT_NUMBER=${MYSQL_PORT}
        - MYSQL_MASTER_HOST=mysql-master
        - MYSQL_MASTER_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      networks:
        - backend

```
