### ISSUE TITLE
Container crashes when persistent data detected

### ISSUE THREAD

**Issue by digitalkaoz** [bitnami/bitnami-docker-mysql#69]
## Description

Sometimes it happens that the Container crashes when there are persistent data. (fails only sometimes)

### Dockerfile

```
FROM bitnami/mysql:5.7

ENV MYSQL_ROOT_PASSWORD=test
ENV MYSQL_USER=test
ENV MYSQL_PASSWORD=test
ENV MYSQL_DATABASE=test

ADD ./*.sql /docker-entrypoint-initdb.d/
```

### Compose File

```yaml
version: "3"

services:
  db:
    image: "custom-mysql:latest" #built from the above
    ports:
      - "13306:3306"
    volumes:
      - db:/bitnami/mysql/data
    environment:
      BITNAMI_DEBUG: "true"

volumes:
  db:
```

**Steps to reproduce the issue:**

1. `docker-compose down -v` (clean volumes and everythin)
2. `docker-compose up` (start from pristine state)
3. `docker-compose stop` (stop everything)
4. `docker-compose up` (will fail, eventually)

**Describe the results you received:**

```
Welcome to the Bitnami mysql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MySQL setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
INFO  ==> Initializing mysql database...
DEBUG ==> Ensuring expected directories/files exist...
DEBUG ==> Creating main configuration file...
INFO  ==> Persisted data detected. Restoring...
INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
DEBUG ==> Executing /docker-entrypoint-initdb.d/001_Initial_schema.sql
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)
INFO  ==> Stopping mysql...
```

**Describe the results you expected:**

clean startup of the mysql container

**Version**

docker: (OSX) `Docker version 18.09.0, build 4d60db4`

- Output of `docker info`:

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 28
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.855GiB
Name: linuxkit-025000000001
ID: BZMH:SB4V:Y55L:3GDB:2MFF:CPFE:6SLZ:OF4V:NXLI:NY2V:552F:PHWT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 53
 System Time: 2019-04-27T01:16:03.5690936Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

* Docker for MAC Version 2.0.0.0-mac82 (29268)

**Comment by tompizmor** [comment]
I would try to see the content of the mysql log file. You can do this:

1. Modify your docker-compose file to execute a custom command:

```
version: "3"

services:
  db:
    image: "custom-mysql:latest" #built from the above
    command: sleep infinity
    ports:
      - "13306:3306"
    volumes:
      - db:/bitnami/mysql/data
    environment:
      BITNAMI_DEBUG: "true"

volumes:
  db:
```

2. Launch docker-compose and connect to the container
3. Initialize MariaDB executing the command `/entrypoint.sh /run.sh`. 
4. Once the previous command fails, you will still be connected to the container and you can inspect the logs at `/opt/bitnami/mariadb/logs`
