### ISSUE TITLE
Slave cannot start when using docker-compose 3.7 version

### ISSUE THREAD

**Issue by chanjarster** [bitnami/bitnami-docker-mysql#71]
**Description**

Slave cannot start when using following docker-compose file:

```yaml
version: '3.7'

services:
  mysql-master:
    image: 'bitnami/mysql:8.0'
    ports:
      - '3307:3306'
    networks:
      - mysqlnet
    volumes:
      - 'mysql_master_data:/bitnami/mysql/data'
    environment:
     - MYSQL_REPLICATION_MODE=master
     - MYSQL_REPLICATION_USER=repl
     - MYSQL_REPLICATION_PASSWORD=password
     - MYSQL_ROOT_PASSWORD=my_root_password
     - MYSQL_USER=my_user
     - MYSQL_PASSWORD=my_database_password
     - MYSQL_DATABASE=my_database
  mysql-slave:
    image: 'bitnami/mysql:8.0'
    ports:
      - '3308:3306'
    networks:
      - mysqlnet
    environment:
     - MYSQL_REPLICATION_MODE=slave
     - MYSQL_REPLICATION_USER=repl
     - MYSQL_REPLICATION_PASSWORD=password
     - MYSQL_MASTER_HOST=mysql-master
     - MYSQL_MASTER_PORT_NUMBER=3306
     - MYSQL_MASTER_ROOT_PASSWORD=my_root_password
```

**Steps to reproduce the issue:**

1. `docker-compose -p mysql-repl up`
2. connect to slave: `docker exec -it mysql-repl_mysql-slave_1 mysql -u root -p`

**Describe the results you received:**

```
Enter password:my_root_password
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

**Describe the results you expected:**

Slave can be connected.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`:

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 354
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: yact0jsdibjh2eh2fc1r7oihq
 Is Manager: true
 ClusterID: 5du8fexyuu9jp8z9xg5p7uk26
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.222.3
 Manager Addresses:
  192.168.222.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 2.441GiB
Name: linuxkit-025000000001
ID: 72CV:SYEV:U2C2:ME7K:TVTM:5RHT:GSEM:T5JZ:TLQZ:EPLL:TF2I:N3BI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 87
 Goroutines: 264
 System Time: 2019-06-18T08:26:42.5088401Z
 EventsListeners: 3
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 172.50.0.0/16
 127.0.0.0/8
Registry Mirrors:
 https://b3vc7vtn.mirror.aliyuncs.com/
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by alemorcuq** [comment]
Hi, @chanjarster.

I'm not able to reproduce your issue. Using this `docker-compose.yml`:

```
version: '3.7'

services:
  mysql-master:
    image: 'bitnami/mysql:8.0'
    ports:
      - '3307:3306'
    environment:
     - MYSQL_REPLICATION_MODE=master
     - MYSQL_REPLICATION_USER=repl
     - MYSQL_REPLICATION_PASSWORD=password
     - MYSQL_ROOT_PASSWORD=my_root_password
     - MYSQL_USER=my_user
     - MYSQL_PASSWORD=my_database_password
     - MYSQL_DATABASE=my_database
  mysql-slave:
    image: 'bitnami/mysql:8.0'
    ports:
      - '3308:3306'
    environment:
     - MYSQL_REPLICATION_MODE=slave
     - MYSQL_REPLICATION_USER=repl
     - MYSQL_REPLICATION_PASSWORD=password
     - MYSQL_MASTER_HOST=mysql-master
     - MYSQL_MASTER_PORT_NUMBER=3306
     - MYSQL_MASTER_ROOT_PASSWORD=my_root_password
```

Then running:

```
$ docker-compose -p mysql-repl up
$ docker exec -it mysql-repl_mysql-slave_1 mysql -u root -p
Enter password:my_root_password
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 25
Server version: 8.0.16 Source distribution

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

Works for me. However, I see that you have a volume attached to your `mysql-master` service. It's possible that you have some persisted data there and, because of that, the password of the root user may not be `my_root_password`. Could you check that?

Regards,
Alejandro
