### ISSUE TITLE
bitnami/mysql:5.7 container restart problem on macOS Catalina

### ISSUE THREAD

**Issue by somodikrisztian1** [bitnami/bitnami-docker-mysql#80]
**Description**
Bitnami mysql container works fine after creation, but everytime a container restart occurs it gets into a stop-start loop.

I create the bitnami/mysql:5.7 container with docker-compose up with an init sql script inside docker-entrypoint-initdb.d folder. After creation the container is healthy and everything is fine, but when I restart it the container gets into a loop. Reading the logs it says Starting mysql in background, Stopping mysql.

**Steps to reproduce the issue:**

1. create a bitnami mysql 5.7 container with some initial data from sql file.
2. wait till container starts up healthy
3. restart the container
4. The container will run in a loop and will never get healthy status

**Describe the results you received:**
<img width="755" alt="Screenshot 2019-12-02 - 3 08 36" src="https://user-images.githubusercontent.com/6016503/69925817-2c687980-14b2-11ea-90a3-77ec47731c2f.png">

**Describe the results you expected:**
The container should restart normally, and become healthy at the end.

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens every time I restart the container. I couldn't solve this issue, so I have to recreate the whole container after the container restarted. This is quite annoying considering all data is inside the container.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 15
  Running: 12
  Paused: 0
  Stopped: 3
 Images: 25
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.65GiB
 Name: docker-desktop
 ID: 2LXY:AAQD:S5G4:TTAR:VQSI:POA3:37VC:SEH4:G5RW:H42C:X4JA:CT25
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 127
  Goroutines: 126
  System Time: 2019-12-02T02:22:55.615889314Z
  EventsListeners: 4
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
## Host computer
macOS Catalina 10.15.1
Mac Pro (Early 2009)
Processor: 3,33 GHz 6-Core Intel Xeon
Memory:  32GB 1333 MHz DDR3
Startup Disk: SSD

## Docker Desktop Community
![Screenshot 2019-12-02 at 3 25 00](https://user-images.githubusercontent.com/6016503/69926380-8a965c00-14b4-11ea-9191-36876cb62170.png)

## Docker Desktop advanced settings
![Screenshot 2019-12-02 at 3 25 29](https://user-images.githubusercontent.com/6016503/69926403-9d109580-14b4-11ea-9261-20c4a79661a0.png)

## docker-compose
```yaml
mysql:
    image: bitnami/mysql:5.7
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - "3306:3306"
    healthcheck:
      test: bash -c "[ -f /bitnami/mysql/.mysql_initialized ]" && mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE} --silent --execute "SHOW TABLES;"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      TZ: Europe/Budapest
    volumes:
      - ${EXTRA_DATA_PATH}/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf
      - ${EXTRA_DATA_PATH}/scripts/:/docker-entrypoint-initdb.d/
      - ${EXTRA_DATA_PATH}/log:/opt/bitnami/mysql/data/
```
