### ISSUE TITLE
How to access phpMyAdmin from bitnami container?

### ISSUE THREAD

**Issue by richb201** [bitnami/bitnami-docker-mysql#81]
I see the configuration and directions for using phpMyAdmin on a regular remote server. On my AWS server I have set up putty (as instructed) with a tunnel to 127.0.0.1. Worked fine. Now I have moved over to Docker on my Ubuntu laptop.  Here is my .yml file. My code can access the mySQL data fine. But I need to manually go into phpMyAdmin to monify some structures. How do I do that from my linux host? I am not using putty in my Docker setup. Do I need to ?

mysql:
    container_name: "mysql"
    restart: unless-stopped
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    volumes:
      - data:/var/lib/mysql
      - ./mysql/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    ports:
      - "3308:3306"
    networks:
      - net

**Comment by sameersbn** [comment]
Assuming phpmyadmin is running on a remote server getting it to communicate with the local mysql instance would be hard (not impossible). 

The simpler option is to deploy PHPMyAdmin locally using the `bitnami/phpmyadmin` docker image and configure it to communicate with the `mysql` instance. Please take a look at https://github.com/bitnami/bitnami-docker-phpmyadmin#how-to-use-this-image

**Comment by cjohnweb** [comment]
This is similar to what I am trying to do, using docker-compose to run both mysql and phpmyadmin. The following docker-compose file works so long as you allow it to create the volume, but if the volume already exists or if you change the password after setting up the volume, it seems mysql will die (and restart and die over and over). The only other thing you have to do is write your variables to a file named `.env`:

## .env
```
MYSQL_USER=root
MYSQL_HOST=127.0.0.1
MYSQL_PORT=3306
MYSQL_DB=testdb
MYSQL_ROOT_PASSWORD=Pass(word123)
ALLOW_EMPTY_PASSWORD=no
PHPMYADMIN_HTTP_PORT=4324
```

## docker-compose.yml
```
---
version: "3.4"
services:
  db:
    image: "bitnami/mysql:5.7"
    user: root
    container_name: db
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - db
    volumes:
      - projectvolume:/bitnami/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      ALLOW_EMPTY_PASSWORD:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_HTTP_PORT}:80"
    networks:
      - db
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: "${MYSQL_PORT}"
networks:
  db:
    driver: bridge
volumes:
  projectvolume:
```
