### ISSUE TITLE
How to re-create a slave?

### ISSUE THREAD

**Issue by marknguyen85** [bitnami/bitnami-docker-mysql#96]
OS: ubuntu 16.04
docker version: 19.03.1
docker-compose: version 1.24.1,
mysql: 8.0.17

my slave-server is failed (not sync with master server) then i ran again a slave by command 

```
$ docker-compose restart mysql-slave
mysql-slave_1   |  23:53:31.16 INFO  ==> ** Starting MySQL setup **
mysql-slave_1   |  23:53:31.22 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql-slave_1   |  23:53:31.23 INFO  ==> Initializing mysql database
mysql-slave_1   |  23:53:31.25 INFO  ==> Using persisted data
mysql-slave_1   |  23:53:31.27 INFO  ==> Running mysql_upgrade
mysql-slave_1   |  23:53:31.28 INFO  ==> Starting mysql in background
```
and its hang long time at that step, then i re-created with command
```
docker-compose up --force-recreate mysql-slave

mysql-slave_1   |  00:28:20.56 
mysql-slave_1   |  00:28:20.56 Welcome to the Bitnami mysql container
mysql-slave_1   |  00:28:20.57 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
mysql-slave_1   |  00:28:20.57 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
mysql-slave_1   |  00:28:20.57 Send us your feedback at containers@bitnami.com
mysql-slave_1   |  00:28:20.57 
mysql-slave_1   |  00:28:20.57 INFO  ==> ** Starting MySQL setup **
mysql-slave_1   |  00:28:20.64 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql-slave_1   |  00:28:20.65 INFO  ==> Initializing mysql database
mysql-slave_1   |  00:28:20.66 INFO  ==> Installing database
mysql-slave_1   |  00:28:24.46 INFO  ==> Starting mysql in background
mysql-slave_1   |  00:28:25.48 INFO  ==> Configuring authentication
mysql-slave_1   |  00:28:25.49 INFO  ==> Configuring replication in slave node
```
and its also hang at this step.

plz give for me an advise to resolves this issue.

**Comment by juan131** [comment]
Hi @marknguyen85 

It looks like an issue in the credentials the slave is using to connect the master node. Could you please the `docker-compose.yaml` you're using? Thanks in advance.

**Comment by marknguyen85** [comment]
> Hi @marknguyen85
> 
> It looks like an issue in the credentials the slave is using to connect the master node. Could you please the `docker-compose.yaml` you're using? Thanks in advance.

my docker-compose file here 
```
version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}

services:

### MySQL Replica################################################
    mysql-master:
      build:
        context: ./mysql2
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
          - TZ=${WORKSPACE_TIMEZONE}
      ports:
        - "${MYSQL_PORT}:3306"
      restart: always
      volumes:
        - ${DATA_PATH_HOST}/mysql-persistence:/bitnami/mysql
        - ./mysql2/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
      environment:
        - MYSQL_REPLICATION_MODE=master
        - MYSQL_REPLICATION_USER=${MYSQL_SLAVE_USER}
        - MYSQL_REPLICATION_PASSWORD=${MYSQL_SLAVE_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      networks:
        - backend
    mysql-slave:
      build:
        context: ./mysql2
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
          - TZ=${WORKSPACE_TIMEZONE}
      ports:
        - "${MYSQL_PORT_SLAVE}:3306"
      volumes:
        - ./mysql2/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
      restart: always
      environment:
        - MYSQL_REPLICATION_MODE=slave
        - MYSQL_REPLICATION_USER=${MYSQL_SLAVE_USER}
        - MYSQL_REPLICATION_PASSWORD=${MYSQL_SLAVE_PASSWORD}
        - MYSQL_MASTER_PORT_NUMBER=${MYSQL_PORT}
        - MYSQL_MASTER_HOST=mysql-master
        - MYSQL_MASTER_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      networks:
        - backend
```
and  `my_custom.cnf`

```
[mysqld]
bind-address=0.0.0.0 
character-set-server=utf8mb4
collation-server=utf8mb4_general_ci
default_authentication_plugin=mysql_native_password
sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
```
'Dockerfile'

```
ARG MYSQL_VERSION=8.0.17
FROM bitnami/mysql:${MYSQL_VERSION}

#####################################
# Set Timezone
#####################################
USER root
ARG TZ=${TZ}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# switch to default user
USER 1001
```
